### ISSUE TITLE
Phase 2 Quality Check 

### ISSUE THREAD

**Issue by AymenFJA** [iceberg-project/ASIFT#3]
Hello @mmacferrin , 

I was starting to build  "Phase2"  in the ASIFT  workflow diagram, and I have questions :

1. Is there any data dependencies?? I mean what is the inputs for the RANSAC filter.

2. Can provide more details about phase 2 conditional branch please, and what is the output of the RANSAC Quality Filter.

Thanks.

**Comment by mmacferrin** [comment]
@AymenFJA, I am uploading v2 of the ASIFT executable code today. I have several sample images I'll need to figure out where to upload (get some space on Bridges or elsewhere) so we can play with the code and adjust it.

The RANSAC filter is not yet implemented, but is coming very soon. It should only require input from the ASIFT outputs, along with the original inputs into ASIFT (i.e. the geolocations of points from the original WorldView imagery). There should be no other data dependencies needed for it.

The RANSAC quality filter will take the matching keypoints between each image that ASIFT outputs, and filter out false-positives. It may filter out up to 90% of the points in some cases. What will result is a SUBSET of points in which there is a higher confidence of being correct matches. It will generate no new points on its own.

Since it hasn't been implemented yet though, it's hard for me to make 100% predictions on how well it'll work, I'm still currently making tweaks to the ASIFT algorithm and image inputs to get better results from that. This is very iterative right now.

**Comment by iparask** [comment]
Hello @AymenFJA @mmacferrin! May I suggest to use the development method that is described in the [Development, Branching and Issue Trecking procedure](https://github.com/iceberg-project/ICEBERG-administration/wiki/Development,-Branching,-and-Issue-Tracking-procedure)?

I know it become cumbersome initially, but it will help greatly to avoid conflicting branches, especially between master and devel.

@AymenFJA please merge master with devel.

Thank you
Giannis

**Comment by mmacferrin** [comment]
Giannis, yes, thank you. To be fair, @AymenFJA was using the protocols correctly, I did not when I created my "mmacferrin" branch off "master", ignored "devel", created a pull request then merged it myself back into "master." Reading your link I can see that was not the best way to do this AT ALL and I will be better about it from here.

I can work with @AymenFJA to get the devel and master branches synced again. I'll create my own branch directly from "devel", make changes from there, and put in a pull request (for review) when the code is ready for another look. When I make such a request, who should I tag to review it?
