### ISSUE TITLE
Error While trying to "make" ASIFT_V2

### ISSUE THREAD

**Issue by AymenFJA** [iceberg-project/ASIFT#5]
Hello @mmacferrin I was trying to cmake and make the ASIFT_V2 on BRIDGES  and i was following  the instructions in the readme file for the ASIFT_V2, when I try to ```  make ``` I am getting this error
```
In file included from /home/aymen/SummerRadical/ASIFT_V2/ASIFT/PHASE_1_KEYPOINT_GENERATION/fast_imas_IPOL/main.cpp:15:0:
/home/aymen/SummerRadical/ASIFT_V2/ASIFT/PHASE_1_KEYPOINT_GENERATION/fast_imas_IPOL/imas.h:30:35: fatal error: opencv2/xfeatures2d.hpp: No such file or directory
 #include <opencv2/xfeatures2d.hpp>
                                   ^
compilation terminated.
make[2]: *** [CMakeFiles/main.dir/main.cpp.o] Error 1
make[1]: *** [CMakeFiles/main.dir/all] Error 2
make: *** [all] Error 2
```

Any ideas ???

**Comment by mmacferrin** [comment]
Aymen,

You'll want to open up the "README.md" file for instructions on building the executable. The OpenCV library (v3.2+) needs to be installed in the user environment before making the fast_imas_IPOL executable. The CMakeLists.txt file should be modified to say where on the local machine the OpenCV libraries are installed... I think right now it's pointing to where they were on my box but that's likely not where they are on yours.

In related news, a new feature was just added to "fast_imas_IPOL" this past weekend to resolve a question I had for the developers of that project. See here: https://github.com/rdguez-mariano/fast_imas_IPOL/issues/1

This means it can now process TIFF images (and GeoTIF specifically) instead of just PNG files, which is very excellent for us. It also means we'll need to install GDAL on the target/user machine as well. I'll make a Git pull request to modify the "fast_imas_IPOL" executable to the latest version there.  I am building it and testing it myself tomorrow and will make the pull request once I verify that it works.  Coming soon.

Let me know if you have any other questions about it.

- Mike
