### ISSUE TITLE
ASIFT Dataset and Images 

### ISSUE THREAD

**Issue by AymenFJA** [iceberg-project/ASIFT#6]
Hi @mmacferrin , 

Can you provide me with high-resolution image samples for the ASIFT just like adam1 and adam2 (but with a bigger size) about between (250MB ~500 MB)? I was trying to design some experiments on the ASIFTv2 and I need these images

**Comment by mmacferrin** [comment]
Aymen,
Apologies for my non-responsiveness lately. Yes, I can get you images matching those descriptions. Thankfully in the newest ASIFT executable we don't need to use PNGs and we can use the TIFFs in a "tiled" fashion (specifying a subset of the target image over which to search) which will help the executable manage memory issues. We just need to do some bookkeeping in post-processing to put the data matches back together again.

I will post a few dropbox links here shortly.

**Comment by mmacferrin** [comment]
Aymen, if you look in the "mmacferrin" branch of the ASIFT repository I have the v2.1 code that can read/write TIF images instead of just PNGs.  I could either make a pull request or you could clone it and migrate it over to your "devel" branch as you see fit. Your code should work exactly the same on it, it just adds "-im1_gdal" & "-im2_gdal" line arguments to use GeoTIFF images instead of just PNGs.

I know you've been looking at SIFT and SURF algorithms, which we can certainly use, but the advantage of ASIFT is being able to use oblique images and account for camera tilt, which SIFT and SURF can't account for. All those algorithms are implemented & available in the v2.1 code, reading the "fast_imas_IPOL/README.md" file explains the command-line options available there. If there are performance issues with the algorithm as its currently implemented then obviously going to a custom implementation may make more sense.

I have TIF images ready to use, that I'm using now. I cannot put them in the Git for space considerations, as well as the fact that they are licenced WorldView images. My email is "michael.macferrin@colorado.edu" and I can send you a dropbox link offline to get a handful of larger TIFs.  I am using a couple of them right now for performance testing.  Just let me know.

**Comment by AymenFJA** [comment]
Hey, @mmacferrin thanks for the explanation, I will keep this issue open and I will check the code and see if the performance issue still exist.

For the TIF images, I will contact you about it.
