### ISSUE TITLE
ASIFT-V2 " execution killed with bigger size images  

### ISSUE THREAD

**Issue by AymenFJA** [iceberg-project/ASIFT#7]
Hi @mmacferrin , 

I was trying to give the ASIFT_v2 a try with bigger size images, so I used 2 images (test1.png=250MB and test2.png =177MB) and when I tried to run it I got "bad allocation" error, so I checked my node resources the one that I am executing the code on, and it appears that when I use bigger size images the code use all the resources and then eventually kill the execution of the ASIFT_v2.

also is the ASIFTv2_code only working with Adam1.png and Adam2.png at this moment?

**Comment by mmacferrin** [comment]
Hi Aymen,

It appears that using two large images does indeed max out the memory the algorithm uses. It kinda blows up.

Right now I'm testing the v2.1 of the "fast_IMAS_IPOL" code, which has the ability to read in GeoTIF's directly using GDAL (no more PNG conversions) and--more imporantly--allows you to designate a tile of the image to use rather than the whole thing. This should really help I think.  We will need to do comparisons with the full-sized WorldView satellite images in a tiled manner and then bring it all together in post-processing, which we can do.  Obviously having nodes with larger memory allocations helps but won't entirely solve it.

At least, that's the plan I'm using right now, if we can find other workarounds we're free to use them.

- Mike

**Comment by AymenFJA** [comment]
Thanks @mmacferrin 

I will close this ticket because we already moved to ASIFTv2.1.
